Update updating-to-parent-repo.yml

diff --git a/.github/workflows/updating-to-parent-repo.yml b/.github/workflows/updating-to-parent-repo.yml
--- a/.github/workflows/updating-to-parent-repo.yml
+++ b/.github/workflows/updating-to-parent-repo.yml
@@ -10,15 +10,15 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Find invalid Markdown files
-          run: |
-            invalid_files=$(find . -type f -name '*.md' ! -regex '.*/[^0-9][a-zA-Z0-9_]*\.md' -print)
-            if [ -n "$invalid_files" ]; then
-              echo "Invalid Markdown file names found:"
-              echo "$invalid_files"
-              exit 1
-            else
-              echo "All Markdown file names are valid."
-            fi
+        run: |
+          invalid_files=$(find . -type f -name '*.md' ! -regex '.*/[^0-9][a-zA-Z0-9_]*\.md' -print)
+          if [ -n "$invalid_files" ]; then
+            echo "Invalid Markdown file names found:"
+            echo "$invalid_files"
+            exit 1
+          else
+            echo "All Markdown file names are valid."
+          fi
       - name: Checkout repository
         uses: actions/checkout@v4
         with:
